Vagrant.configure("2") do |config|
  config.vm.define "lab1b" do |lab1b|
    lab1b.vm.box = "ubuntu/xenial64"
    lab1b.vm.box_version = "20180511.0.0"
    lab1b.vm.hostname = "lab1b"
    lab1b.vm.network "private_network", ip: "172.17.17.11"
    lab1b.vm.provider "virtualbox" do |vb|
      vb.memory = 512
    end
  end
end
