Vagrant.configure("2") do |config|
  config.vm.define "lab1a" do |lab1a|
    lab1a.vm.box = "centos/7"
    lab1a.vm.box_version = "1801.02"
    lab1a.vm.hostname = "lab1a"
    lab1a.vm.network "private_network", ip: "172.17.17.11"
    lab1a.vm.provider "virtualbox" do |vb|
      vb.memory = 512
    end
  end
end

